# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
env:
  global:
    - JULIA_NUM_THREADS=4
addons:
  apt:
    packages:
      - gfortran
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - echo "travis_fold:start:TPT-install"
 - julia -e 'Pkg.clone(pwd()); Pkg.build("TPT")'
 - echo "travis_fold:end:TPT-install"
 - echo "travis_fold:start:DepPkg-install"
 - julia -e 'Pkg.add("GR"); Pkg.build("GR")'
 - julia -e 'Pkg.add("Plots"); Pkg.build("Plots")'
 - julia -e 'using GR'
 - julia -e 'using Plots'
 - echo "travis_fold:end:DepPkg-install"
 - julia -e 'Pkg.test("TPT"; coverage=false)'
