# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
env:
  - JULIA_NUM_THREADS=4
  - secure: "szTFeKxp0PaJFQ0c3hljmAx3a6y3T1wq7IliJUIsV9dGPKg7lQad7dTjBwS5zYVpGN3TD0h5Wf8AAOgSgg5SvS+L3e2NKfjs9lfs5qTxRSbAv6DFNf8XfNii5UnJcP1BDk8j2ZgN1gYye0uXg1Ptie71Lbr0LHizsIOdPvPvg65lW7kb3io4mMFf4wExzGKuY1QFa3fJkXJCLTKwGqhwLGNtYyy1nnD0rlaDxEliEg/CBd70opPHp0/Dv/+SSLgCQLWRYkLysa+xE4U1kL5TLCld4eDyI0NjFNp3QqTqqbESuMvbZpvSYv4yxrkI/3CXRZGNKphwl/oZk1PRTtjZjrWFWO5VS3nFSg5L9OSTZFzxfTh1R3J7QP+974naP10bqQs+Xc3IdOC/NIG2LnkqlMT46zr4ngT0zsar86wjhKILwO+oMza4P+eg0AvfNScfGK6n55B+8ir6rRA9f+yaCJKw5mPd/4S67ZEg+n2H6oQ/+tVBkGG3S9aCULSBZCXW7WPcfQWt1EhyGrOIHknj7mBm1vUWFbPSzg43uNx0t0HZA1CNZNwzt/0SGV6CI7pIkoy5+x+C2rgwonzRFZHq+ZH3fystFP9D58eVvoTvFDtx3LU2/By2qlLKKceF207cK5PBmDbbSsr/AS1FBg1Wh0oMsKoxFv7yHIvJVbD4XH8="
  - secure: "K2FK9R6OUC18JcXYb7AbM9oflrWttEmTVe4ITk9GR4iEHh3jgBr1x7A7cbbVoullhWvipzA+04peCyRG6sesxMZRL9YQAGAoaYMO2IezKZtBkPDorILmicRm38AHLtiE+DexkvDkldcHYA+dlB8oAxHq7iV3lo/MpwWo6LTEWySJjTu9oMhpLdSVzg7RFJxKDVPDBwgUSQdxnkhfkzceKGcs67NGyqBxkp+58argF3EgTrP8OpGajBN+yXrwoTO8ImeJ/Pz/1TY7qJcy9fgmDp6WMeZsTfdDJky25ew5dOJ8rwpl9z3OQf6cAWyHhFhovYXFYjnbkiuM/4O8X/BOOnrCmD5IylZWuf6FHXe5lT7F+b2+a+xHrmPh6Tay67suq1Hu17hBrgS+Wy9J6fZqjoLKDEvMg/9m28qsnm+cDcZixt4ZEzrVgaGdtVeiOTWt2mAWUPvbFm+KU+HC8GEI6Ep9DrPdt4doBWwnYcN0Yxm1PI0qyXDadRqBJAdBczIdw+lpl6qcRSM3adwuxYG/bU7TJquknHrzoxESQZVJ7lNaLxbMDi9tGVQM6Li01Ip1Fh9uwt5oOpOqYrmdOyzqay3iPwjjxbnFd4MGJ3rxBJ3KCZYqdDKL8FJ8JqnexlVP36ETULtbkWolQdndVHbs8HzVIP+Ap0MckOs4nCzzVMI="
addons:
  apt:
    packages:
      - gfortran
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - echo "travis_fold:start:TPT-install"
 - julia -e 'Pkg.clone(pwd()); Pkg.build("TPT")'
 - echo "travis_fold:end:TPT-install"
 - echo "travis_fold:start:Pkg-install"
 - julia -e 'Pkg.add("DataFrames"); Pkg.build("DataFrames"); using DataFrames'
 - julia -e 'Pkg.add("Plots"); Pkg.build("Plots"); using Plots'
 - julia -e 'ENV["PYTHON"] = ""; Pkg.add("PyPlot"); Pkg.build("PyPlot"); using PyPlot'
 - echo "travis_fold:end:Pkg-install"
 - julia -e 'Pkg.test("TPT"; coverage=false)'
after_success:
 - ./.travis.sh
