# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
env:
  global:
    - JULIA_NUM_THREADS=4
    - secure: "lrr3f55etozw0s47lBFDfiHFvfyN3CmFs7EvPXYg5SoNeKCBgDIN6Wgqr4iOqNucKa8mD16kD9QYI0REtX0zNIexT6/q23jTwU26AuL16gN2ZrswpTo6SPlE7vycXi+Ei8hAXxouMPD2XggOPygKnJOLXWzFGBWoKGqMNzTqPE9DPy8Lgv4pcTlvbO9tCJQ7eEFZGkacKMKHPyYRpsJhF1kRSVM/iioiYWNkJmUa8DHJeRkZ18fiRetnoGWRGF8ZBy1na8KuMkV8OoL4vKcRpKuEjfQ0WdlpBAXzQHoC5ARtleZfqMX+MmpHgYjFi3UnH+5HhE49Xoor6DXQkt6g9rElPPZGqisSfDq0svIW63KFRPfVeGbQbad5f/eakObFqGLPvoUocbinDfFUJwBApFBZWLxLBA8jyp4LKJ4JQJSVdvkbmAOG9nLgYqli3urPZKe1nsbF7l6DhhdlZ4rnwSJMY/zRtHvKk5dLVqI7WIX2sF3jDhpXCz8mFBcsj5aIchYQNIolChwXFRwjkqhLajZdd+cYa4+87RMwNFQpPR5g/g8zgS5EURwC1XnMwPeOMv1YhWvpJgKnTx9mJrxRIZE8zdcuOjW0zOMfjTvEKLGggFTVr7pdwEDW31rfqUEGEAMtdDQRI3qujQfyXqHOS8HLgZDFzzKm1Ox1zTVPjEY="
    - secure: "lRS/KJjAYG5YTLZkbk4CtezDzhoNHXzDp8lcM+NgSvGg8uZOA7WFP0BbN3ZJXZSx7txMVw0Ll558e8McXaKJ6Fn43BUtuKvi5G6O3dCjcQ82Iqe5WGAAZ4fRTdVMM5spJy5JM0veCfg5Eujk5r7cyXTxAv1iHSUtBenWxXIZLxKE1RwYnwNK+Ebt/lnai9a6C6PDs/SltreASxLy/S/i7Uxb5WPOpdtSzc5l5fOeGWF2vf5NtXino+2sTgf/XbqYmK/tItPhgoLzf6JSLEGqZ4QFiBAZ84stqSf1oVHgKQBvZuQKRpZNKR3yXZYe3YgVz2hR1px8b+CuXpAUFkuNWFp0C5a/gy7xeDiwWXq4y2AMGDnH9962oHoyR5ySd3RbzG3+Kn1R80lwxGvXmkUEULtV54a+H3ULdEzcglj1SJ4izV5uOUaPNRsHVUuQciRELP7C44+zoIiJFnTMM7dXZDZ6ihE7kBPqoFFueA9DyuCf8mSiLJk3EF1T4V5AHBDIxaJtWEalpmxYxguZKLSOdtbMt0yVrcOe0uB9SqnpfH/lbBO0wOPTU13/XmMoEOoMKYeNURSWXEKG1XzZcGin9IpwtwMSri2uJhagHGXzBIAQoQ4st6DHjxiiYr/OH9I7iKQqeRqKUQRokK01GN+Xa5FFA074sfO0Y5PhXMh2xhI=" 
addons:
  apt:
    packages:
      - gfortran
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - echo "travis_fold:start:TPT-install"
 - julia -e 'Pkg.clone(pwd()); Pkg.build("TPT")'
 - echo "travis_fold:end:TPT-install"
 - echo "travis_fold:start:Pkg-install"
 - julia -e 'Pkg.add("DataFrames"); Pkg.build("DataFrames"); using DataFrames'
 - julia -e 'Pkg.add("Plots"); Pkg.build("Plots"); using Plots'
 - julia -e 'ENV["PYTHON"] = ""; Pkg.add("PyPlot"); Pkg.build("PyPlot"); using PyPlot'
 - echo "travis_fold:end:Pkg-install"
 - julia -e 'Pkg.test("TPT"; coverage=false)'
after_success:
 - ./.travis.sh
